### ISSUE TITLE
Considering dropping HHVM support

### ISSUE THREAD

**Issue by ronanguilloux** [ronanguilloux/IsoCodes#103]
Is anyone using HHVM here?

Cf. https://github.com/symfony/symfony/issues/18922

**Comment by Soullivaneuh** [comment]
No for my case.

But the code is actually running on HHVM without hack.

Maybe can we keep this and consider dropping it later if we have to do too much hacks and if HHVM will be very less used?

**Comment by Soullivaneuh** [comment]
I also launched a subject for Sonata: https://github.com/sonata-project/dev-kit/issues/126

**Comment by ronanguilloux** [comment]
If no energy/interest to support HHVM is found here, we'll consider putting an end to HHVM support, unless any good contribution may put HHVM travis builds into green again.

**Comment by Soullivaneuh** [comment]
You can also leave it on allow failure waiting that.

The `fast_finish` option would help to get rid of allowed failure jobs for PR status: https://blog.travis-ci.com/2013-11-27-fast-finishing-builds/

**Comment by Soullivaneuh** [comment]
BTW, test itself seems to work: https://travis-ci.org/ronanguilloux/IsoCodes/jobs/133623468#L384

The error come from another thing...

Can you remember me why you put `-d error_reporting=16384` option? I don't use it at all on my projects.

**Comment by ronanguilloux** [comment]
Because of : "In September 2017, it was announced that version 3.24 would be the last version of HHVM to officially support PHP, and that HHVM will only support Hack going forward, citing differences and incompatibilities in PHP 7." (_Source: https://en.wikipedia.org/wiki/HHVM_)
this issue will now be closed.
