### ISSUE TITLE
Add more options to phone validator

### ISSUE THREAD

**Issue by oscarotero** [ronanguilloux/IsoCodes#105]
To validate phones, this library uses [giggsey/libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php) that returns more information than simply check whether the number is correct or not. I think it would be great to have more validation options like check whether the phone is a mobile or not. For example:

``` php
$isValidMobile = Phone::validate($number, 'US', ['type' => 'mobile']);
```

**Comment by Soullivaneuh** [comment]
@oscarotero see also: https://github.com/ronanguilloux/IsoCodes/issues/113

**Comment by ronanguilloux** [comment]
Check whether the phone is a mobile or not is about identifying, **_guessing_**, rather than validating. Guessing values types would be a great project, but that would be another lib's topic.
