### ISSUE TITLE
GB postcode regex contains ungrouped alternatives

### ISSUE THREAD

**Issue by kitbs** [ronanguilloux/IsoCodes#108]
The regex for GB (and others?) ZIP/ postal codes in [ZipCode.php](https://github.com/ronanguilloux/IsoCodes/blob/master/src/IsoCodes/ZipCode.php) uses alternatives separated by `|` which are not wrapped in an overall `(...)` group.

When the `^` and `$` anchors are added in [L228](https://github.com/ronanguilloux/IsoCodes/blob/master/src/IsoCodes/ZipCode.php#L228), they only get attached to the first and last alternatives, instead of to the whole expression.

So the regex lets through non-valid postcodes, e.g. "CR0 3RL" will match just as well as "anystuffbefore CR0 3RL anyjunkattheend".

Am raising a PR to fix.

**Comment by ronanguilloux** [comment]
merged=>closed
