### ISSUE TITLE
Missing test class for Gtin13

### ISSUE THREAD

**Issue by Soullivaneuh** [ronanguilloux/IsoCodes#115]
But another Gtin validators have corresponding tests. Maybe a miss?

I also saw missing test for `Dun14`, `Itf14` and `Upca`, but I'm suppose because they are deprecated. Am I right?

**Comment by ronanguilloux** [comment]
- `Ean13Test` existed before `Gtin13Test` which is then an alias. We maintain Ean13 as it's still a widely used alt name for Gtin13. No need to duplicate tests.
- Dun14, Itf14, and Upc-A are GTIN-* aliases
