### ISSUE TITLE
Wrong Iban length for SE

### ISSUE THREAD

**Issue by julkido** [ronanguilloux/IsoCodes#116]
Hello,

The rule for validating Sweden IBAN are wrong because the length without SE is 22 characters

https://en.wikipedia.org/wiki/International_Bank_Account_Number

**Comment by Soullivaneuh** [comment]
Hi @julkido,

Could you please provide some not valid IBAN examples?

**Comment by julkido** [comment]
I just figured out that it wasn't the problem, a substr is done before the preg_match so the tested length is 20 characters.

```
$check = substr($iban, 4);
preg_match('~^'.$rules[$ctr].'$~', $check)
```

I am trying to figure out why "SE2880000832790000012345" is not valid using this bundle.

Thx!

**Comment by julkido** [comment]
Ok actually the checksum of this IBAN is not correct according to this website too: http://www.ibancalculator.com/iban_validieren.html

Sorry for the inconvenience!
