### ISSUE TITLE
Singleton class for SSN

### ISSUE THREAD

**Issue by Soullivaneuh** [ronanguilloux/IsoCodes#12]
The SSN validator is special. We have to instantiate it before use it for validation.

I think is for avoid code generation (`generate('CA')`) on each validation?

In this case, could we think about use it as a singleton class?

See here (FR): http://fr.wikipedia.org/wiki/Singleton_%28patron_de_conception%29#PHP_5

I suggest it because with this code design, I will have to instantiate it on each validation with my Symfony Validator wrapping.

Could work on it. This should be on a next major release.

**Comment by ronanguilloux** [comment]
Please send a PR

**Comment by Soullivaneuh** [comment]
Will work on it.

Just to show you the problem:

 * All constraint call your validators like this: https://github.com/Soullivaneuh/IsoCodesValidator/blob/597486d1eb96717ffd3408d3ed7864e07e6476fd/src/Constraints/VatValidator.php#L23
 * En for SSN: https://github.com/Soullivaneuh/IsoCodesValidator/blob/597486d1eb96717ffd3408d3ed7864e07e6476fd/src/Constraints/SsnValidator.php#L24-L26

As you can see, I have to instantiate this class for each validation.

**Comment by Soullivaneuh** [comment]
The [generate](https://github.com/ronanguilloux/IsoCodes/blob/ce766e240c1776f31d8cf6c7a6184fb2c67d060c/src/IsoCodes/Ssn.php#L256) method of `Ssn` is never called from class validation.

What is the goal of this method?

**Comment by ronanguilloux** [comment]
To generate a SSN, based on state.

**Comment by Soullivaneuh** [comment]
But it is not used for validation, is it?

If not, are you OK to make it static too?

**Comment by Soullivaneuh** [comment]
Closed for #34.
