### ISSUE TITLE
SIRET Issue with "La Poste" according INSEE

### ISSUE THREAD

**Issue by Geolim4** [ronanguilloux/IsoCodes#134]
Hello,

According Wikipedia, the following exception exists and should be taken in consideration:
https://fr.wikipedia.org/wiki/Formule_de_Luhn#Cas_particulier

**Comment by Geolim4** [comment]
Technical details here:
https://groupes.renater.fr/sympa/nomenu/arc/pstage-utilisateurs/2014-02/msg00035.html

**Comment by Geolim4** [comment]
bum @ronanguilloux ;)
Do you accept PRs ?

**Comment by ronanguilloux** [comment]
oh yes sure!
https://github.com/ronanguilloux/IsoCodes/blob/master/CONTRIBUTING.md

**Comment by Geolim4** [comment]
Ok, I'll have a look this weekend. Do you think that adding that (La POSTE) "exception" confirmed by INSEE looks ok in that project ?

**Comment by Geolim4** [comment]
Ohh right, you're a Nantais too :P
I'll take a look this weekend between some shifts, Luhn's abstract is fine, but the SIREN/SIRET must extends it more "intelligently" :)

**Comment by PastisD** [comment]
Hello @Geolim4,

I've the same issue. Did you had time to check it ? :)

**Comment by Geolim4** [comment]
I'll take a look this weekend and let you know :)

**Comment by Geolim4** [comment]
Here ya go folks: #136

**Comment by Geolim4** [comment]
Once merged, let's take that beer at the Chat Qui Pète ^^
