### ISSUE TITLE
Packagist is not updated automatically

### ISSUE THREAD

**Issue by stof** [ronanguilloux/IsoCodes#142]
Packagist does not have the 2.1.6 release, and the master branch still points at https://github.com/ronanguilloux/IsoCodes/commit/7ad5cd60bf5a84611d07292b5b3436d6c4b4865d

This is probably related to not having migrated the auto-update to the new github integration of Packagist and still relying on the old github service system, which has now been shutdown by github.

Please configure the auto-update again for Packagist (and force an update if needed).

**Comment by stof** [comment]
@ronanguilloux any chance to fix this ?

**Comment by ronanguilloux** [comment]
Hi @stof,
Looks like https://packagist.org/packages/ronanguilloux/isocodes is now up to date, with `dev-master` pointing at latest commits. Do you confirm it?

**Comment by stof** [comment]
yes it looks OK. What I cannot check is whether it will stay uptodate (i.e. is the github integration in place) or whether it was fixed by the monthly crawl done as fallback.

**Comment by ronanguilloux** [comment]
All good, and stays uptodate thanks to the Github integration, tags available ASAP on https://packagist.org/packages/ronanguilloux/isocodes.
