### ISSUE TITLE
Vérification du numéro de sécurité sociale incomplet

### ISSUE THREAD

**Issue by SylvainSimon** [ronanguilloux/IsoCodes#146]
Bonjour, 

Je me permet de rédiger ce ticket en Français car je veut juste aller droit au but.
Il y'a un soucis dans la vérification des numéro de sécurité sociales.

Une patiente (Car je travail avec un médecin généraliste) à pour numéro de sécurité sociale sur sa carte : 2 60 07 20 *** *** **.

Vous remarquerez que le département indiqué est "20", ce qui correspond a la Corse en générale, Là où on se serait attendu a trouver 2A ou 2B. Sauf que ce numéro existe belle est bien et que tu coups la vérification par expression régulière retourne une erreur.

Je travail avec la version 2.2.1 de la librairie. Cela bloque évidemment mon business puisque la patient ne peut pas être intégré dans notre applicatif.

Pouvez-vous regarder si il ne faudrait pas mettre un peut à jours ce code de vérification Insee ?

Cordialement,

**Comment by ronanguilloux** [comment]
Effectivement, en cherchant un peu je trouve plusieurs validations ou l'on replace le A ou le B par un zero. Et Wikipedia indique que cette règle a changé "après le 1er janvier 1976".

Un petite contribution ?

**Comment by SylvainSimon** [comment]
Euh sur le papier on a juste a autoriser le 20 dans l'expression régulière ? J'ai un peu du mal a comprendre cette partie de ton expression

(?<departement>[02][1-9]|2[AB]|[1345678][0-9]|9[012345789])

Il suffit juste de rajouter le 2 dans [12345678][0-9] non ?

Je vois aussi en testant l’expression que 96 est refusé, c'est normal ? Je ne vois aucune exception à ce sujet dans la documentions Wikipédia.

**Comment by ronanguilloux** [comment]
For the record:

le `2 dans [1345678][0-9]`, ça donne en fait [1-8][0-9]. C'est mis à jour avec d'autres nouvelles vérifs.

`Sauf erreur le 96 est refusé, c'est normal`: le 96 ne devrait pas être refusé, c'est désormais accepté.

**Comment by SylvainSimon** [comment]
After update and check with differents inseee number, it's seems to be invalid for the number "150082B05104034"

On website like http://mon-convertisseur.fr/calculateur-cle-numero-securite-sociale.php?MODECALC=AVANCE&SBM=Passez+en+mode+avanc%C3%A9 this number is valid.

![image](https://user-images.githubusercontent.com/11244274/69815862-8558b900-11f7-11ea-9575-f8cc2b52d0b4.png)

Can you check why the number is not validate by your library ?
