### ISSUE TITLE
[Insight] The composer.lock is not up to date. - in composer.lock, line 0

### ISSUE THREAD

**Issue by ronanguilloux** [ronanguilloux/IsoCodes#16]
**[in composer.lock](https://github.com/ronanguilloux/IsoCodes/blob/ea3d5e0467bf45195bf3cfba12782f5fb84966c6/composer.lock#L0)**

> The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/fde42adb-344d-4055-b78d-20b598040ac8/analyses/16)_

**Comment by Soullivaneuh** [comment]
Is the composer.lock really necessary for a library?

**Comment by ronanguilloux** [comment]
Thanks for pointing this out:

We usually wouldn't have to.
Anyway, in our particular case, having many --dev related vendors (see usages in `Makefile`), with some unstable ones, I found it useful for contributors to always test against the same dependency versions.

Not a big issue, anyway ;-)
