### ISSUE TITLE
GTIN Checksum Calculator

### ISSUE THREAD

**Issue by pableu** [ronanguilloux/IsoCodes#165]
Would you be interested in a PR to **calculate** the checksum for GTIN or EAN codes? This could be useful, I have an application where I generate new GTINs within our assigned range.

The interface could be like this: 

```php
\IsoCodes\Gtin14::checksum(1234567890123); // returns 1
```

Or

```php
\IsoCodes\Gtin14::addChecksum(1234567890123); // returns 12345678901231
```

**Comment by ronanguilloux** [comment]
Hi @pableu,
Thanks a lot for your suggestion!

That project is really aimed to solve the validation of formats, hence the [simplistic Interface contract](https://github.com/ronanguilloux/IsoCodes/blob/master/src/IsoCodes/IsoCodeInterface.php) that only expects a `validate()` method to be implemented. That global contract makes the lib easy to understand and augment.

Now, proposing the calculation for checksums to many codes would be a great, still demanding evolution. And proposing these checksums calculations to only a few codes, as an exception, is not my preferred approach.

I'm open to that evolution, but only if someone can actually deliver a solid coverage of such a new feature – and related tests, to at least 2/3 of the codes that we are currently supporting.

**Comment by pableu** [comment]
I see and I understand your argumentation. 

I think right now I'd feel confident about doing it for GTIN and EAN, that's only 7 out of all the supported codes. 

Maybe I'll create a PR when I find the time to dig into this more deeply and do it for more codes. I think there are more codes than just the GTINs where it'd be possible to calculate the check-digit.
