### ISSUE TITLE
PHP8 compatibility

### ISSUE THREAD

**Issue by tquensen** [ronanguilloux/IsoCodes#166]
composer.json defines `"php": "^7"` as requirement, which prevents installing on PHP8

I suggest changing this to `"php": ">=7"` or `"php": "^7|^8"`

PHPUnit runs fine in PHP8.0 (OK (1096 tests, 1924 assertions))

**Comment by ronanguilloux** [comment]
released in the latest 2.3.2 tag - thanks to @janlanger - see #167
