### ISSUE TITLE
Replace deprecated PHPUnit  `strict` option

### ISSUE THREAD

**Issue by ronanguilloux** [ronanguilloux/IsoCodes#20]
PHPUnit versions have deprecated the `strict` option, thus this message is shown for every invocation:

`Deprecated configuration setting "strict" used`

See #13 and https://travis-ci.org/ronanguilloux/IsoCodes/jobs/59845136

**Comment by Soullivaneuh** [comment]
What should we do? Just remove `strict="true"` from [this line](https://github.com/ronanguilloux/IsoCodes/blob/master/phpunit.xml.dist#L2)?

Do you have the related doc?

**Comment by ronanguilloux** [comment]
Only saw this explicit warning message in Travis trace: 
This come from PHPUnit 4.5.0 release https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-4.5.0

**Comment by Soullivaneuh** [comment]
So we just have to remove this option.
