### ISSUE TITLE
The PHP 5.3 build cannot install dependencies

### ISSUE THREAD

**Issue by stof** [ronanguilloux/IsoCodes#24]
The requirements cannot be resolved on 5.3 currently, making the Travis job useless

**Comment by ronanguilloux** [comment]
fixed in 1a1a1953dbb93df6c161b26b92e1c63d1234fd2c

**Comment by Soullivaneuh** [comment]
@ronanguilloux Composer requirement should be updated too: https://github.com/ronanguilloux/IsoCodes/blob/master/composer.json#L20
