### ISSUE TITLE
+1 UK PostCode, UK Tax Code

### ISSUE THREAD

**Issue by ronanguilloux** [ronanguilloux/IsoCodes#41]
http://www.braemoor.co.uk/software/vat.shtml

**Comment by Soullivaneuh** [comment]
UK vat should be on `Vat` validator, isn't it?

For post code, please see #38 before. :+1:

**Comment by barryvdh** [comment]
It is:
`'GB' => '\d{9}|\d{12}|(GD|HA)\d{3}',`

You could also validate by api:
https://github.com/viruschidai/validate-vat

**Comment by Soullivaneuh** [comment]
Title should be updated, post code is already implemented here: https://github.com/ronanguilloux/IsoCodes/blob/c027b47e2738bdb68308b2963f5d850b5e94dfd0/src/IsoCodes/ZipCode.php#L77

**Comment by ronanguilloux** [comment]
- GB VAT tax code validation [already implemented](https://github.com/ronanguilloux/IsoCodes/blob/2.0.0/src/IsoCodes/Vat.php#L39)
- UK ZipCode [already implemented](https://github.com/ronanguilloux/IsoCodes/blob/2.0.0/src/IsoCodes/ZipCode.php#L77)
