### ISSUE TITLE
+1 per-country bank account validation rules

### ISSUE THREAD

**Issue by ronanguilloux** [ronanguilloux/IsoCodes#43]
cf. http://www.credit-card.be/BankAccount/ValidationRules.htm

**Comment by Soullivaneuh** [comment]
With maybe same method as #38, if accepted.

**Comment by ronanguilloux** [comment]
From 2008, SEPA payment-integration initiative of the European Union set up both [IBAN](https://github.com/ronanguilloux/IsoCodes/blob/master/src/IsoCodes/Iban.php) (International Bank Account Number) and [SWIFT/BIC](https://github.com/ronanguilloux/IsoCodes/blob/master/src/IsoCodes/SwiftBic.php) (Bank Identifier Code) as new ISO standards for bank transactions. National validation rules are less relevant.
