### ISSUE TITLE
+1 IMEI (International Mobile Station Equipment Identity) validator

### ISSUE THREAD

**Issue by ronanguilloux** [ronanguilloux/IsoCodes#48]
Luhn-based. May be an occasion for refactoring all Luhn-based validations

**Comment by Soullivaneuh** [comment]
Which existing validators are Luhn-based too?

**Comment by ronanguilloux** [comment]
[Please use the search bar](https://github.com/ronanguilloux/IsoCodes/search?utf8=%E2%9C%93&q=Luhn&type=Code)

**Comment by Soullivaneuh** [comment]
Indeed. Want to be sure if this is not commented on all validators. :+1:
