### ISSUE TITLE
Remove old Ssn instantiation method

### ISSUE THREAD

**Issue by Soullivaneuh** [ronanguilloux/IsoCodes#52]
Remove `$fromInstance` flag from `Ssn` constructor and make it `private`.

Don't forget to remove the flag from `getInstance` constructor call too.

@ronanguilloux Can you add this todo on 2.0 milestone?

Related to #34.

**Comment by Soullivaneuh** [comment]
@ronanguilloux This issue should be for next major release `2.0`, not `1.2`. ;-)

**Comment by ronanguilloux** [comment]
Closed by merging #73

**Comment by Soullivaneuh** [comment]
Why reopen it?
