### ISSUE TITLE
php with bcmath required for some checks but not mentioned in the docs

### ISSUE THREAD

**Issue by tsfoer** [ronanguilloux/IsoCodes#7]
PHP is required to be compiled with "--enable-bcmath" for some checks but this is not mentioned in the documentation.
Please update the documentation or provide a fallback method if possible.

Thomas

**Comment by ronanguilloux** [comment]
- Concerned classes: Iban & Bban
- Concerned BCMath function: [bcmod](http://php.net/manual/en/function.bcmod.php)
- Alternatives to explore : `%`, (php modulus operator)

**Comment by ronanguilloux** [comment]
Thanks !

Reminder for GNU/Linux, Debian-based Ubuntu OS : 

> `php5-fpm` in `Precise` and later as well as the Apache equivalent `libapache2-mod-php5` package for Apache built-in PHP5 modules is listed as having `bcmath` built in to it as an included module. This information is written in the package description file (debian/control) in the package itself when extracted and being viewed as the raw source package, containing source code and a debian/ directory which contains directives to debian build systems to build packages.

([source](http://askubuntu.com/a/416875))

**Comment by tsfoer** [comment]
Wow, that was quick!

Thanks a lot :)

**Comment by Soullivaneuh** [comment]
@ronanguilloux I still think bc-math extension should be optionnal and only suggested.

In replacement, we can throw proper exception if bc-math is not implemented on needed validator.

What do you think? I could propose a PR about that.

**Comment by ronanguilloux** [comment]
OK for a PR!

**Comment by Soullivaneuh** [comment]
Ok I'll work on it but not those days. I'll open another issue to get it on memory! :+1:
