### ISSUE TITLE
SsnTest failing on windows

### ISSUE THREAD

**Issue by enumag** [ronanguilloux/IsoCodes#74]
SsnTest is failing if the Ssn.php file has CRLF end of lines instead of just LF. I tried to fix it using some line normalization function but it didn't work for unknown reason.

This should be considered a bug, the script should not depend on the EOL style used since that can be changed unpredictably when deploying for example.

**Comment by Soullivaneuh** [comment]
I'm not sure of what you mean. Would you like to work on PR for test proof and fix?

**Comment by enumag** [comment]
Unfortunately I didn't manage to fix it. That's why I've only sent an issue instead of a PR.
