### ISSUE TITLE
CreditCardTest failing on windows

### ISSUE THREAD

**Issue by enumag** [ronanguilloux/IsoCodes#75]
Test for [this card number](https://github.com/ronanguilloux/IsoCodes/blob/c027b47e2738bdb68308b2963f5d850b5e94dfd0/tests/IsoCodes/Tests/CreditCardTest.php#L33) fails on windows because a number this long can't be stored as an integer. Instead it becomes a float and when converted into string it is `6.3041E+15` instead of `6304100000000008`.

In my opinion `CreditCard::validate` should only allow string arguments or at least throw an exception if a float is passed as parameter to prevent this error.

**Comment by Soullivaneuh** [comment]
Bug confirmed: https://ci.appveyor.com/project/Soullivaneuh/isocodesvalidator/build/68/job/yi9niguhr76allvd#L260

**Comment by Soullivaneuh** [comment]
@ronanguilloux I can help to configure appveyor CI if you want. Just tell me! ;-)

**Comment by ronanguilloux** [comment]
64-bit platforms usually have a maximum value of about 9E18, except on Windows prior to PHP 7, where it was always 32 bit.
No final decision here, and no troll either (really), but IMHO, it is not the IsoCodes project responsibility to handle Microsoft Windows limitations on implementing of the integer type.
Quick-win: use Vagrant/Docker/WhateverVirtualMachineEngine instead.

**Comment by Soullivaneuh** [comment]
I understand your point of view about 32/64 bits issue.

But apart of this, do this make sens to validate an integer for a credit card serial? It should be a string IMHO.

If you accept #93, you will earn two thing: 32 bit compatibility and stricter comparison.

If I was a Windows user, I would prefer having the same return value on both 32/64 bit system.

**Comment by Soullivaneuh** [comment]
> it is not the IsoCodes project responsibility to handle Microsoft Windows limitations on implementing of the integer type.

It's an understandable decision, but in this case I think you should add a note that you don't support any 32 bits OS anymore.

And not only Windows. 32bits linux system should have the same issue. We didn't see it on Travis because it run only 64bits builds AFAIK.

**Comment by ronanguilloux** [comment]
> It's an understandable decision, but in this case I think you should add a note that you don't support any 32 bits OS anymore.

=> OK for that.

> And not only Windows. 32bits linux system should have the same issue. We didn't see it on Travis because it run only 64bits builds AFAIK.

=> https://github.com/travis-ci/travis-ci/issues/986#issuecomment-124141683 : not in current Travis roadmap.

**Comment by Soullivaneuh** [comment]
> => travis-ci/travis-ci#986 (comment) : not in current Travis roadmap.

Yes, this is why I'm saying that 32bits linux must has this bug too, but we can't see it on Travis. :wink: 


My final opinion for this issue is: We should invalid integer values on this validator because passing an integer for a credit card serial make no sense. It's a serial, not a number.

And I think it not really worth to drop 32 bits support just for this case.

**Comment by ronanguilloux** [comment]
See https://github.com/ronanguilloux/IsoCodes/pull/93#issuecomment-219216161 => no merge for now => put that in the fridge for a next major release.
