### ISSUE TITLE
English code and comment?

### ISSUE THREAD

**Issue by Soullivaneuh** [ronanguilloux/IsoCodes#9]
Hi and thanks for this project, found a lot of missing validators.

I'm planning to wrap them with a Symfony [Validator](https://github.com/symfony/Validator) extension, I'll speak about it later! :-)

Have you plan to normalize code on command to get it on full English?

Could make thinks easier for world wide contributing.

Some french code here, for example: https://github.com/ronanguilloux/IsoCodes/blob/master/src/IsoCodes/OrganismeType12NormeB2.php
And spanish comments here: https://github.com/ronanguilloux/IsoCodes/blob/master/src/IsoCodes/Nif.php

Regards

**Comment by ronanguilloux** [comment]
planned

**Comment by Soullivaneuh** [comment]
:+1:
